server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
      enabled: true # Enable http encoding support
      force: true

spring:
  application:
    name: topjava26-project-kubatko
    version: '@project.version@'

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:voting;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:

  sql:
    init:
      data-locations: classpath:db/data.sql

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  mvc.pathmatch.matching-strategy: ant_path_matcher
  jmx.enabled: false

  cache:
    cache-names: users
    caffeine.spec: maximumSize=1, expireAfterAccess=60s

springdoc:
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: true
    path: /swagger-ui.html
    url: /v3/api-docs
  show-actuator: false

app:
  vote-deadline-time: '11:00'

logging:
  level:
    root: WARN
    ru.skubatko.dev: INFO
