spring:
  application:
    name: topjava26-project-kubatko
    version: '@project.version@'
  profiles:
    active: dev

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  liquibase:
    enabled: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    disable-swagger-default-url: false
    use-root-path: true
    path: /swagger-ui.html
  show-actuator: false

logging:
  level:
    root: WARN
