server:
  port: 8081

spring:
  application:
    name: topjava26-project-kubatko
    version: '@project.version@'

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:topjava;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:

  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    disable-swagger-default-url: false
    use-root-path: true
    path: /swagger-ui.html
  show-actuator: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.orm.jpa: DEBUG
    ru.skubatko.dev: TRACE
