server:
  port: 8081

logging:
  charset.console: UTF-8
  pattern.console: '%white([%thread]) %highlight(%-5level) %cyan(%logger{5}) %magenta([%file:%-4L]) - %msg%n'
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.orm.jpa: INFO
    org.hibernate: INFO
    ru.skubatko.dev: INFO
