openapi: 3.0.0
info:
  title: topjava26-project-rest-heartbeat-v1
  version: 1.0.0
  description: 'TopJava Project. Heartbeat API'
servers:
  - url: 'http://localhost:8080'
    description: LOCAL
paths:
  /heartbeat/v1/ping:
    summary: Heartbeat signal (ping)
    get:
      tags:
        - heartbeat
      operationId: ping
      summary: Heartbeat signal (ping)
      responses:
        '200':
          description: OK
          content:
            text/plain;charset=utf-8:
              schema:
                type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
