openapi: 3.0.0
info:
  title: topjava26-project-rest-admin-users-v1
  version: 1.0.0
  description: 'TopJava Project. Admin users API'

servers:
  - url: 'http://localhost:8080'
    description: Local

paths:
  /api/admin/v1/users:
    get:
      operationId: getAll
      summary: Get list of available users
      description: Получение списка пользователей
      tags:
        - adminUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 100000
                items:
                  type: string
                  format: user
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
    post:
      operationId: create
      summary: Create user
      description: Создание пользователя
      tags:
        - adminUser
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: user
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
                format: user
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
  /api/admin/v1/users/{id}:
    get:
      operationId: get
      summary: Get user
      description: Получение пользователя по идентификатору
      tags:
        - adminUser
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: user
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
    put:
      operationId: update
      summary: Update user
      description: Обновление данных пользователя по идентификатору
      tags:
        - adminUser
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: user
        required: true
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
    patch:
      operationId: enable
      summary: Enable/disable user
      description: Включение/отключение пользователя
      tags:
        - adminUser
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/enabled'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
    delete:
      operationId: delete
      summary: Delete user
      description: Удаление пользователя по идентификатору
      tags:
        - adminUser
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
  /api/admin/v1/users/by-email:
    get:
      operationId: getByEmail
      summary: Get user by email
      description: Получение пользователя по email
      tags:
        - adminUser
      parameters:
        - $ref: '#/components/parameters/email'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: user
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable

components:
  parameters:
    id:
      name: id
      description: Идентификатор
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 2147483647
    email:
      name: email
      description: Email
      in: query
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 100
    enabled:
      name: enabled
      description: Признак включения
      in: query
      required: true
      schema:
        type: boolean
