openapi: 3.0.0
info:
  title: topjava26-project-rest-admin-v1
  version: 1.0.0
  description: 'TopJava Project. Admin API'
servers:
  - url: 'http://localhost:8080/api'
    description: LOCAL
paths:
  /api/admin/v1/restaurants:
    get:
      operationId: getAll
      summary: Get list of available restaurants
      description: Получение списка ресторанов
      tags:
        - adminRestaurant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 100000
                items:
                  $ref: '#/components/schemas/RestaurantsTO'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
  /api/admin/v1/restaurants/{restaurantId}:
    get:
      operationId: get
      summary: Get restaurant details
      description: Получение описания ресторана по идентификатору
      tags:
        - adminRestaurant
      parameters:
        - $ref: '#/components/parameters/restaurantId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestaurantsTO'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
components:
  schemas:
    RestaurantsTO:
      title: RestaurantsTO
      type: object
      description: Ресторан
      additionalProperties: false
      properties:
        id:
          type: integer
          description: Идентификатор
          format: int32
          minimum: 1
          maximum: 2147483647
        name:
          type: string
          minLength: 2
          maxLength: 100
          description: Название
      required:
        - id
        - name
  parameters:
    restaurantId:
      name: restaurantId
      description: Идентификатор ресторана
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 2147483647
