openapi: 3.0.0
info:
  title: topjava26-project-rest-user-votes-v1
  version: 1.0.0
  description: 'TopJava Project. User votes API'
servers:
  - url: 'http://localhost:8080'
    description: LOCAL
paths:
  /user/v1/votes:
    get:
      operationId: getDaily
      summary: Get vote daily result
      description: Получение итогов голосования за день
      tags:
        - userVote
      parameters:
        - $ref: '#/components/parameters/day'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                maxItems: 100000
                items:
                  $ref: '#/components/schemas/VoteResultTO'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
    post:
      operationId: vote
      summary: Daily lunch vote
      description: Голосование за ресторан
      tags:
        - userVote
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoteStatusTO'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
components:
  parameters:
    day:
      name: day
      description: День голосования
      in: query
      required: true
      schema:
        type: string
        format: date
  schemas:
    VoteTO:
      title: VoteTO
      type: object
      description: Голос за ресторан
      additionalProperties: false
      properties:
        day:
          description: День голосования
          type: string
          format: date
        restaurantId:
          type: integer
          description: Идентификатор ресторана
          format: int32
          minimum: 1
          maximum: 2147483647
        votedAt:
          type: string
          description: Временная метка голосования
          format: time
      required:
        - day
        - restaurantId
        - votedAt
    VoteResultTO:
      title: VoteResultTO
      type: array
      description: Итоги голосования за день
      additionalProperties: false
      properties:
        restaurantId:
          type: integer
          description: Идентификатор ресторана
          format: int32
          minimum: 1
          maximum: 2147483647
        votes:
          type: integer
          description: Количество отданных голосов
          format: int32
          minimum: 0
          maximum: 2147483647
      required:
        - restaurantId
        - votes
    VoteStatusTO:
      title: VoteStatusTO
      type: object
      description: Статус голосования
      additionalProperties: false
      properties:
        status:
          type: string
          description: Статус голосования
      required:
        - status
