openapi: 3.0.0
info:
  title: topjava26-project-rest-user-profiles-v1
  version: 1.0.0
  description: 'TopJava Project. User profiles API'

servers:
  - url: 'http://localhost:8080'
    description: Local

paths:
  /api/user/v1/profiles:
    get:
      operationId: get
      summary: Get user
      description: Получение профиля пользователя
      tags:
        - userProfile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: user
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
    post:
      operationId: register
      summary: Register user
      description: Регистрация пользователя
      tags:
        - userProfile
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: newUser
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
                format: user
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
    put:
      operationId: update
      summary: Update user
      description: Обновление данных пользователя по идентификатору
      tags:
        - userProfile
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: user
        required: true
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
    delete:
      operationId: delete
      summary: Delete user
      description: Удаление профиля пользователя
      tags:
        - userProfile
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
