openapi: 3.0.0
info:
  title: topjava26-project-rest-user-v1
  version: 1.0.0
  description: 'TopJava Project. User API'
servers:
  - url: 'http://localhost:8080/api'
    description: LOCAL
paths:
  /user/v1/vote:
    post:
      operationId: vote
      summary: Daily lunch vote
      description: Голосование за ресторан
      tags:
        - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoteTO'
        required: true
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
components:
  schemas:
    VoteTO:
      title: VoteTO
      type: object
      description: Голос за ресторан
      additionalProperties: false
      properties:
        restaurantId:
          type: integer
          description: Идентификатор ресторана
          format: int32
          minimum: 1
          maximum: 2147483647
        votedAt:
          type: string
          description: Временная метка голосования
          format: time
      required:
        - restaurantId
        - votedAt
