openapi: 3.0.0
info:
  title: topjava26-project-rest-user-v1
  version: 1.0.0
  description: 'TopJava Project. User API'
servers:
  - url: 'http://localhost:8080/api'
    description: LOCAL
paths:
  /user/v1/vote/{restaurantId}:
    post:
      operationId: vote
      summary: Daily lunch vote
      description: Голосование за ресторан
      tags:
        - user
      parameters:
        - $ref: '#/components/parameters/restaurantId'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Access Denied
        '500':
          description: Internal Server Error
components:
  parameters:
    restaurantId:
      name: restaurantId
      description: Идентификатор ресторана
      in: path
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
        maximum: 2147483647
