## Admin Users

### getAll
GET http://localhost:8080/api/admin/v1/users
Authorization: Basic admin@gmail.com admin
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not OK");
});
%}

### get
GET http://localhost:8080/api/admin/v1/users/1
Authorization: Basic admin@gmail.com admin
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not OK");
});
%}

### validate with Unprocessable Entity
POST http://localhost:8080/api/admin/v1/users
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 422, "Response status is not Unprocessable Entity");
});
%}

### validate with Duplicate Email Error
POST http://localhost:8080/api/admin/v1/users
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "email": "guest@mail.ru"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 422, "Response status is not Unprocessable Entity");
});
%}

### create
POST http://localhost:8080/api/admin/v1/users
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "New User",
  "email": "new@gmail.ru",
  "password": "new-password",
  "enabled": true,
  "roles": [
    {
      "role": "ROLE_ADMIN"
    },
    {
      "role": "ROLE_USER"
    }
  ]
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not Created");
});
%}

### update
PUT http://localhost:8080/api/admin/v1/users/5
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "id": 5,
  "name": "updatedUser",
  "email": "updated@gmail.ru",
  "password": "updated-password",
  "enabled": true,
  "roles": [
    {
      "role": "ROLE_ADMIN"
    },
    {
      "role": "ROLE_USER"
    }
  ]
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not NoContent");
});
%}

### delete
DELETE http://localhost:8080/api/admin/v1/users/5
Authorization: Basic admin@gmail.com admin
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not NoContent");
});
%}

###
